"""init

Revision ID: 10d710702866
Revises: 
Create Date: 2026-03-25 17:31:28.874874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d710702866'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rubric_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'teacher', 'superadmin', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leader_user_id', sa.Integer(), nullable=False),
    sa.Column('group', sa.Enum('undergrad', 'postgrad', name='teamgroup'), nullable=False),
    sa.Column('work_name', sa.String(length=500), nullable=False),
    sa.Column('leader_name', sa.String(length=200), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=False),
    sa.Column('college_major', sa.String(length=500), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('member1_name', sa.String(length=200), nullable=False),
    sa.Column('member1_college', sa.String(length=200), nullable=False),
    sa.Column('member1_major', sa.String(length=200), nullable=False),
    sa.Column('member2_name', sa.String(length=200), nullable=False),
    sa.Column('member2_college', sa.String(length=200), nullable=False),
    sa.Column('member2_major', sa.String(length=200), nullable=False),
    sa.Column('member3_name', sa.String(length=200), nullable=False),
    sa.Column('member3_college', sa.String(length=200), nullable=False),
    sa.Column('member3_major', sa.String(length=200), nullable=False),
    sa.Column('advisor_name', sa.String(length=200), nullable=True),
    sa.Column('advisor_college', sa.String(length=200), nullable=True),
    sa.Column('advisor_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['leader_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leader_user_id')
    )
    op.create_index(op.f('ix_teams_group'), 'teams', ['group'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('paper_pdf_anonymous_path', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('teacher_user_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', name='scorestatus'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'teacher_user_id', name='uq_submission_teacher')
    )
    op.create_index(op.f('ix_scores_submission_id'), 'scores', ['submission_id'], unique=False)
    op.create_index(op.f('ix_scores_teacher_user_id'), 'scores', ['teacher_user_id'], unique=False)
    op.create_table('score_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('rubric_item_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['rubric_item_id'], ['rubric_items.id'], ),
    sa.ForeignKeyConstraint(['score_id'], ['scores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('score_id', 'rubric_item_id', name='uq_score_rubric_item')
    )
    op.create_index(op.f('ix_score_items_rubric_item_id'), 'score_items', ['rubric_item_id'], unique=False)
    op.create_index(op.f('ix_score_items_score_id'), 'score_items', ['score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_items_score_id'), table_name='score_items')
    op.drop_index(op.f('ix_score_items_rubric_item_id'), table_name='score_items')
    op.drop_table('score_items')
    op.drop_index(op.f('ix_scores_teacher_user_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_submission_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_teams_group'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_table('rubric_items')
    # ### end Alembic commands ###